### PR TITLE
Setup devise

### PR DESCRIPTION
**Pull request by EdwinNgn**
please add you comment

### CODE REVIEW

**Comment by RoseRoseM** [comment]
great job team let's roll

**Comment by Tomzer42** [comment]
It seems to be good !

**Comment by EdwinNgn** [comment]
@Tomzer42 can you please merge the branch ?

**Comment by Tomzer42** [comment]
Yes I can @EdwinNgn

**Comment by Tomzer42** [comment]
@paulchapeau Do you hear me ?

**Pull request merged**
